### ISSUE TITLE
Google Voice Search not working

### ISSUE THREAD

**Issue by SammysHP** [jrizzoli/vendor_google#8]
See here: http://forum.xda-developers.com/htc-one-s/help/cm-12-1-nighty-20150503-ok-google-t3100265

Google hotword detection as well as regular voice search is not working with this gapps-package. The user in the thread tried another gapps-package with the same ROM version and it is working.

**Comment by jrizzoli** [comment]
It has been already fixed. It will work in next update. If you cant wait, find the so files on prebuilts/arm/lib/, download them and put them on the system/lib

**Comment by SammysHP** [comment]
Thanks for the quick response! The weird thing: I looked at the HEAD and thought that it matches the latest release. :/

**Comment by jrizzoli** [comment]
I forgot to push those files on arm, I did just did it on arm64

**Comment by SammysHP** [comment]
I extracted

```
/system/lib/libgoogle_hotword_jni.so
/system/lib/libgoogle_recognizer_jni_l.so
/system/lib/libvcdecoder_jni.so
```

from the original Nexus 4 Android 5.1 factory image (`libgoogle_hotword_jni.so` and `libvcdecoder_jni.so` in your package had different checksums) and symlinked them from `/system/priv-app/Velvet/lib/arm`).

Still does not work. :(

**Comment by jrizzoli** [comment]
Maybe u forgot to chmod them. If u have a Linux / Unix PC u can compile gappsso you'll be sure everything is right

**Comment by SammysHP** [comment]
root:root with 644, so everything right. Something else must be missing. Sadly no hint in logcat when trying to create my voice profile in Google Search.

**Comment by SammysHP** [comment]
I'm using http://fitsnugly.euroskank.com/?rom=banks&device=gapps now. That one works great. Maybe you can find any difference.
